[features]
seeds = false
[programs.devnet]
gifly = "BsauxuUC9tQMiQjK3ChKpUn9TUnTmGjfA6dQgP7zzgpJ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/joshchoi/.config/solana/devnet.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
